name: Deploy
on:
  push:
    branches:
      - main
    tags:
      - "!*"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: LLK/scratch-gui
          ref: v3.6.18
      - run: npm install
      - uses: actions/checkout@v4
        with:
          path: ./stretch3

      - run: sh ./stretch3/add_ga_tracking_code.sh
      - run: NODE_OPTIONS=--openssl-legacy-provider npm run build
      - run: sh ./stretch3/modify_index_html.sh
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
          publish_branch: master
